# Generated by Django 2.2.7 on 2020-01-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchesBetweenTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_match', models.DateField(blank=True, null=True)),
                ('elected_to', models.CharField(blank=True, max_length=10, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, max_length=700, null=True, upload_to='team/logo/')),
                ('club_state', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsPerSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serieswiseteams', to='cricket.Series')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_per_series', to='cricket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_played', models.IntegerField(default=0)),
                ('match_won', models.IntegerField(default=0)),
                ('match_lost', models.IntegerField(default=0)),
                ('match_tied', models.IntegerField(default=0)),
                ('no_result', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('net_runrate', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pt_series', to='cricket.Series')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pt_team', to='cricket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, max_length=700, null=True, upload_to='player/profile/')),
                ('jersey_num', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cricket.Country')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_of_the_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_performer', to='cricket.Player')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='cricket.MatchesBetweenTeams')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='cricket.Team')),
            ],
        ),
        migrations.AddField(
            model_name='matchesbetweenteams',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='cricket.Series'),
        ),
        migrations.AddField(
            model_name='matchesbetweenteams',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='matchesbetweenteams',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='matchesbetweenteams',
            name='toss_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_winner', to='cricket.Team'),
        ),
        migrations.CreateModel(
            name='BowlingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.IntegerField(default=0)),
                ('ball', models.IntegerField(default=0)),
                ('run', models.IntegerField(default=0)),
                ('wicket', models.IntegerField(default=0)),
                ('best_bowling', models.CharField(blank=True, max_length=10, null=True)),
                ('econ', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('strike_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('avgs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cricket.Player')),
            ],
        ),
        migrations.CreateModel(
            name='BattingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.IntegerField(default=0)),
                ('ball_faced', models.IntegerField(default=0)),
                ('run', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('strike_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('avgs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cricket.Player')),
            ],
        ),
    ]
