# Generated by Django 2.2.7 on 2020-01-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battinghistory',
            old_name='match',
            new_name='match_played',
        ),
        migrations.RenameField(
            model_name='bowlinghistory',
            old_name='econ',
            new_name='economy',
        ),
        migrations.RenameField(
            model_name='bowlinghistory',
            old_name='match',
            new_name='match_played',
        ),
    ]
