# Generated by Django 2.2.7 on 2020-01-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20200110_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchesbetweenteams',
            name='elected_to',
        ),
        migrations.RemoveField(
            model_name='matchesbetweenteams',
            name='toss_winner',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='winner',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='elected_to',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='match_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner_team', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='toss_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_winner', to='cricket.Team'),
        ),
    ]
