# Generated by Django 2.2.7 on 2020-01-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_auto_20200112_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='player_team', to='cricket.Team'),
            preserve_default=False,
        ),
    ]
