# Generated by Django 2.2.7 on 2020-01-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0006_auto_20200113_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battinghistory',
            old_name='avgs',
            new_name='bt_avgs',
        ),
        migrations.RenameField(
            model_name='battinghistory',
            old_name='match_played',
            new_name='bt_match_played',
        ),
        migrations.RenameField(
            model_name='battinghistory',
            old_name='run',
            new_name='bt_run',
        ),
        migrations.RenameField(
            model_name='battinghistory',
            old_name='strike_rate',
            new_name='bt_strike_rate',
        ),
        migrations.RenameField(
            model_name='bowlinghistory',
            old_name='avgs',
            new_name='bl_avgs',
        ),
        migrations.RenameField(
            model_name='bowlinghistory',
            old_name='run',
            new_name='bl_run',
        ),
        migrations.RenameField(
            model_name='bowlinghistory',
            old_name='strike_rate',
            new_name='bl_strike_rate',
        ),
        migrations.RemoveField(
            model_name='bowlinghistory',
            name='match_played',
        ),
        migrations.AddField(
            model_name='bowlinghistory',
            name='bt_match_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchesbetweenteams',
            name='match_no',
            field=models.IntegerField(default=1),
        ),
    ]
