# Generated by Django 2.2.7 on 2020-01-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0007_auto_20200116_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_series', to='cricket.Series'),
        ),
    ]
